export default [    
    { name: 'Cấp đổi, cấp lại giấy chứng nhận đủ điều kiện về an ninh, trật tự để kinh doanh một số ngành, nghề kinh doanh có điều kiện', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp giấy chứng nhận đủ điều kiện về an ninh, trật tự để kinh doanh một số ngành, nghề kinh doanh có điều kiện', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Đăng ký, cấp biển số xe', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Đăng ký xe đối với xe mô tô điện, xe máy điện', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp lại giấy chứng nhận đăng ký xe, biển số xe bị mất', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Đổi lại giấy chứng nhận đăng ký xe, biển số xe', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Thu hồi giấy chứng nhận đăng ký mô tô, xe gắn máy và biển số', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Đăng ký sang tên mô tô, xe gắn máy trong cùng tỉnh', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Sang tên, di chuyển mô tô, xe gắn máy đi tỉnh, thành phố trực thuộc Trung ương khác', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Đăng ký mô tô, xe gắn máy từ tỉnh khác chuyển đến', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp giấy chuyển hộ khẩu', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp huyện' },
    { name: 'Xóa đăng ký thường trú', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Xác nhận việc trước đây đã đăng ký thường trú', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Điều chỉnh những thay đổi trong sổ hộ khẩu', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Thu hồi đất do chấm dứt việc sử dụng đất theo pháp luật, tự nguyện trả lại đất đối với các trường hợp thu hồi đất của hộ gia đình, cá nhân, cộng đồng dân cư, thu hồi đất ở của người Việt Nam định cư ở nước ngoài được sở hữu nhà ở tại Việt Nam.', type: 'Lĩnh vực Tài nguyên', orgProcess: '1. Thủ tục hành chính cấp huyện' },
    { name: 'Tách sổ hộ khẩu', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp huyện' },
    { name: 'Đăng ký thường trú', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp thẻ Căn cước công dân khi chưa có thông tin trong Cơ sở dữ liệu quốc gia về dân cư', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp thẻ Căn cước công dân khi đã có thông tin trong Cơ sở dữ liệu quốc gia về dân cư', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Đổi thẻ căn cước công dân', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp lại thẻ Căn cước công dân', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Xác nhận số Chứng minh nhân dân khi đã được cấp thẻ Căn cước công dân', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Xác nhận số Chứng minh nhân dân khi cấp thẻ Căn cước công dân đã có thông tin trong Cơ sở dữ liệu quốc gia về dân cư.', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Giải quyết khiếu nại về quyết định hành chính, hành vi hành chính của công dân đối với lực lượng Công an nhân dân (phải là cán bộ thuộc biên chế của lực lượng Công an)', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Giải quyết tố cáo không thuộc lĩnh vực tố tụng hình sự của công dân đối với lực lượng Công an nhân dân (phải là cán bộ thuộc biên chế của lực lượng Công an)', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Xác nhận số Chứng minh nhân dân khi cấp thẻ Căn cước công dân chưa có thông tin trong Cơ sở dữ liệu quốc gia về dân cư', type: 'Lĩnh vực Công An', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp Giấy phép bán lẻ sản phẩm thuốc lá', type: 'Lĩnh vực Công Thương', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp sửa đổi, bổ sung Giấy phép kinh doanh bán lẻ sản phẩm rượu', type: 'Lĩnh vực Công Thương', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp lại Giấy phép kinh doanh bán lẻ sản phẩm rượu', type: 'Lĩnh vực Công Thương', orgProcess: 'UBND cấp Huyện' },
    { name: 'Cấp Giấy phép kinh doanh bán lẻ sản phẩm rượu', type: 'Lĩnh vực Công Thương', orgProcess: 'UBND cấp Huyện' },
]