export default [
    { name: 'Quyết định sử dụng tài sản công để tham gia dự án đầu tư theo hình thức đối tác công – tư'},
    { name: 'Quyết định tiêu hủy tài sản công'},
    { name: 'Quyết định thanh lý tài sản công'},
    { name: 'Quyết định bán tài sản công'},
    { name: 'Quyết định điều chuyển tài sản công'},
    { name: 'Quyết định thu hồi tài sản công trong trường hợp thu hồi tài sản công theo quy định tại các điểm a, b, c, d, đ và e khoản 1 Điều 41 của Luật Quản lý, sử dụng tài sản công'},
    { name: 'Quyết định thu hồi tài sản công trong trường hợp cơ quan nhà nước được giao quản lý, sử dụng tài sản công tự nguyện trả lại tài sản cho Nhà nước'},
    { name: 'Quyết định thuê tài sản phục vụ hoạt động của cơ quan, tổ chức, đơn vị'},
    { name: 'Quyết định mua sắm tài sản công phục vụ hoạt động của cơ quan, tổ chức, đơn vị trong trường hợp không phải lập dự án đầu tư'},
    { name: 'Mua hóa đơn lẻ'},
    { name: 'Mua quyển hóa đơn'},
    { name: 'Quyết định xử lý tài sản bị hư hỏng, không sử được hoặc không còn nhu cầu sử dụng trong quá trình thực hiện dự án'},
    { name: 'Quyết định xử lý tài sản phục vụ hoạt động của dự án khi dự án kết thúc'},
    { name: 'Thanh toán chi phí liên quan đến bán tài sản trên đất, chuyển nhượng quyền sử dụng đất'},
    { name: 'Thanh toán chi phí có liên quan đến việc xử lý tài sản công'},
    { name: 'Hoàn trả hoặc khấu trừ tiền sử dụng đất đã nộp hoặc tiền nhận chuyển nhượng quyền sử dụng đất đã trả vào nghĩa vụ tài chính của chủ đầu tư dự án nhà ở xã hội'},
    { name: 'Phê duyệt đề án sử dụng tài sản công tại đơn vị sự nghiệp công lập vào mục đích liên doanh, liên kết'},
    { name: 'Phê duyệt đề án sử dụng tài sản công tại đơn vị sự nghiệp công lập vào mục đích kinh doanh, cho thuê'},
    { name: 'Đăng ký mã số đơn vị có quan hệ với ngân sách'},
]