export default [    
    { shortName: '2.001885.000.00.00.H60', name: 'Cấp Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001884.000.00.00.H60', name: 'Sửa đổi, bổ sung Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001880.000.00.00.H60', name: 'Gia hạn Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001786.000.00.00.H60', name: 'Cấp lại Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001766.000.00.00.H60', name: 'Thông báo thay đổi chủ sở hữu; địa chỉ trụ sở chính của tổ chức, doanh nghiệp đã được cấp Giấy phép thiết lập trang thông tin điện tử tổng hợp', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001765.000.00.00.H60', name: 'Cấp Giấy chứng nhận đăng ký thu tín hiệu truyền hình nước ngoài trực tiếp  từ vệ tinh', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001744.000.00.00.H60', name: 'Cấp lại giấy phép hoạt động in', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '2.001740.000.00.00.H60', name: 'Đăng ký hoạt động cơ sở in', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '2.001737.000.00.00.H60', name: 'Thay đổi thông tin đăng ký hoạt động cơ sở in', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '2.001684.000.00.00.H60', name: 'Thông báo thay đổi địa chỉ trụ sở chính, văn phòng giao dịch, địa chỉ đặt hoặc cho thuê máy chủ của doanh nghiệp cung cấp dịch vụ trò chơi điện tử G1 trên mạng', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001681.000.00.00.H60', name: 'Thông báo thay đổi cơ cấu tổ chức của doanh nghiệp cung cấp trò chơi điện tử G1 trên mạng do chia tách, hợp nhất, sáp nhập, chuyển đổi công ty theo quy định của pháp luật về doanh nghiệp; thay đổi phần vốn góp dẫn đến thay đổi thành viên góp vốn (hoặc cổ đông) có phần vốn góp từ 30% vốn điều lệ trở lên', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001666.000.00.00.H60', name: 'Thông báo thay đổi tên miền khi cung cấp dịch vụ trò chơi điện tử trên trang thông tin điện tử (trên Internet), kênh phân phối trò chơi (trên mạng viễn thông di động); thể loại trò chơi (G2, G3, G4); thay đổi địa chỉ trụ sở chính của doanh nghiệp cung cấp dịch vụ trò chơi điện tử G2, G3, G4 trên mạng', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001594.000.00.00.H60', name: 'Cấp giấy phép hoạt động in xuất bản phẩm', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '2.001584.000.00.00.H60', name: 'Cấp lại giấy phép hoạt động in xuất bản phẩm', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '2.001564.000.00.00.H60', name: 'Thủ tục Cấp giấy phép in gia công xuất bản phẩm cho nước ngoài', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '2.001173.000.00.00.H60', name: 'Cho phép họp báo (nước ngoài)', linhVuc: 'Báo chí', mucDo: 'Toàn trình' },
    { shortName: '2.001171.000.00.00.H60', name: 'Cho phép họp báo (trong nước)', linhVuc: 'Báo chí', mucDo: 'Toàn trình' },
    { shortName: '2.001098.000.00.00.H60', name: 'Cấp Giấy phép thiết lập trang thông tin điện tử tổng hợp', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001091.000.00.00.H60', name: 'Gia hạn Giấy phép thiết lập trang thông tin điện tử tổng hợp', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '2.001087.000.00.00.H60', name: 'Cấp lại Giấy phép thiết lập trang thông tin điện tử tổng hợp', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '1.010902.000.00.00.H60', name: 'Sửa đổi, bổ sung văn bản xác nhận thông báo hoạt động bưu chính cấp Tỉnh', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.009386.000.00.00.H60', name: 'Văn bản chấp thuận thay đổi nội dung ghi trong giấy phép xuất bản bản tin (địa phương)', linhVuc: 'Báo chí', mucDo: 'Toàn trình' },
    { shortName: '1.008201.000.00.00.H60', name: 'Cấp lại giấy xác nhận đăng ký hoạt động phát hành xuất bản phẩm', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.005452.000.00.00.H60', name: 'Sửa đổi, bổ sung Giấy phép thiết lập trang thông tin điện tử tổng hợp', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '1.005442.000.00.00.H60', name: 'Cấp lại văn bản xác nhận thông báo hoạt động bưu chính khi bị mất hoặc hư hỏng không sử dụng được', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.004637.000.00.00.H60', name: 'Cấp giấy phép xuất bản bản tin (địa phương)', linhVuc: 'Báo chí', mucDo: 'Toàn trình' },
    { shortName: '1.004470.000.00.00.H60', name: 'Cấp văn bản xác nhận thông báo hoạt động bưu chính', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.004379.000.00.00.H60', name: 'Cấp lại Giấy phép bưu chính khi bị mất hoặc hư hỏng không sử dụng được', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.004153.000.00.00.H60', name: 'Cấp giấy phép hoạt động in', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.003888.000.00.00.H60', name: 'Trưng bày tranh, ảnh và các hình thức thông tin khác bên ngoài trụ sở cơ quan đại diện nước ngoài, tổ chức nước ngoài', linhVuc: 'Báo chí', mucDo: 'Toàn trình' },
    { shortName: '1.003868.000.00.00.H60', name: 'Cấp giấy phép xuất bản tài liệu không kinh doanh', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.003729.000.00.00.H60', name: 'Cấp đổi giấy phép hoạt động in xuất bản phẩm', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.003725.000.00.00.H60', name: 'Cấp Giấy phép nhập khẩu xuất bản phẩm không kinh doanh', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.003687.000.00.00.H60', name: 'Sửa đổi, bổ sung Giấy phép bưu chính', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.003659.000.00.00.H60', name: 'Cấp giấy phép bưu chính', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.003633.000.00.00.H60', name: 'Cấp lại Giấy phép bưu chính khi hết hạn', linhVuc: 'Bưu chính', mucDo: 'Toàn trình' },
    { shortName: '1.003483.000.00.00.H60', name: 'Cấp giấy phép tổ chức triển lãm, hội chợ xuất bản phẩm', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.003384.000.00.00.H60', name: 'Sửa đổi, bổ sung Giấy chứng nhận đăng ký thu tín hiệu truyền hình nước ngoài trực tiếp từ vệ tinh', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '1.003114.000.00.00.H60', name: 'Cấp giấy xác nhận đăng ký hoạt động phát hành xuất bản phẩm', linhVuc: 'Xuất Bản, In và Phát hành', mucDo: 'Toàn trình' },
    { shortName: '1.000073.000.00.00.H60', name: 'Thông báo thay đổi phương thức, phạm vi cung cấp dịch vụ trò chơi điện tử G1 trên mạng đã được phê duyệt', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },
    { shortName: '1.000067.000.00.00.H60', name: 'Thông báo thay đổi cơ cấu tổ chức của doanh nghiệp cung cấp dịch vụ trò chơi điện tử G2, G3, G4 trên mạng do chia, tách, hợp nhất, sáp nhập, chuyển đổi công ty theo quy định của pháp luật về doanh nghiệp; thay đổi phần vốn góp dẫn đến thay đổi thành viên góp vốn (hoặc cổ đông) có phần vốn góp từ 30% vốn điều lệ trở lên', linhVuc: 'Phát thanh, truyền hình và Thông tin điện tử', mucDo: 'Toàn trình' },

]