deploy-datalake:
  stage: deploy
  image: bitnami/git:2.39.1
  only:
    - datalake
  script:
    - echo "https://bachhs:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    - git config credential.helper 'store --file ~/.git-credentials'
    - git config remote.datalake.url >&- || git remote add datalake https://github.com/bachhs/datalake.git
    - git push datalake HEAD:datalake

deploy-dx:
  stage: deploy
  image: bitnami/git:2.39.1
  only:
    - dx
  script:
    - echo "https://bachhs:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    - git config credential.helper 'store --file ~/.git-credentials'
    - git config remote.dx.url >&- || git remote add dx https://github.com/bachhs/dwh-dx.git
    - git push dx HEAD:dx
