default:
  image: node:16.16.0

deploy-datalake:
  stage: deploy
  image: node:16.16.0
  only:
    - datalake
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

deploy-dx:
  stage: deploy
  image: bitnami/git:2.39.1
  only:
    - dx
  script:
    - echo "https://bachhs:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    - git config credential.helper 'store --file ~/.git-credentials'
    - git config remote.github.url >&- || git remote add github https://github.com/bachhs/dwh-dx.git
    - git push github HEAD:dx