# default:
#   image: node:16.16.0

# deploy_preview:
#   stage: deploy
#   except:
#     - main
#   script:
#     - npm install --global vercel
#     - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
#     - vercel build --token=$VERCEL_TOKEN
#     - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

# deploy_production:
#   stage: deploy
#   only:
#     - main
#   script:
#     - npm install --global vercel
#     - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
#     - vercel build --prod --token=$VERCEL_TOKEN
#     - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

push-to-github:
  stage: deploy
  image: bitnami/git:2.39.1
  only:
    - main-navigation-updated
  script:
    - echo "https://bachhs:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    - git config credential.helper 'store --file ~/.git-credentials'
    - git remote add github https://github.com/bachhs/dwh-dx.git
    - git push github HEAD:main-navigation-updated